export const MESSAGE_LIST_ITEM_CREATE = 'MESSAGE_LIST_ITEM_CREATE';
export const MESSAGE_LIST_ITEM_UPDATE = 'MESSAGE_LIST_ITEM_UPDATE';
export const MESSAGE_LIST_ITEM_DELETE = 'MESSAGE_LIST_ITEM_DELETE';
export const MESSAGE_LIST_ITEM_MOVE = 'MESSAGE_LIST_ITEM_MOVE';
export const MESSAGE_LIST_ITEM_UPVOTE = 'MESSAGE_LIST_ITEM_UPVOTE';
export const MESSAGE_LIST_ITEM_DOWNVOTE = 'MESSAGE_LIST_ITEM_DOWNVOTE';
export const MESSAGE_LIST_ITEM_START_EDITING = 'MESSAGE_LIST_ITEM_START_EDITING';
export const MESSAGE_LIST_ITEM_CANCEL_EDITING = 'MESSAGE_LIST_ITEM_CANCEL_EDITING';
export const MESSAGE_LIST_OPEN_CREATE_NEW_FORM = 'MESSAGE_LIST_OPEN_CREATE_NEW_FORM';
export const MESSAGE_LIST_CLOSE_CREATE_NEW_FORM = 'MESSAGE_LIST_CLOSE_CREATE_NEW_FORM';
export const MESSAGE_LIST_SAVING_STARTED = 'MESSAGE_LIST_SAVING_STARTED';
export const MESSAGE_LIST_SAVING_FINISHED = 'MESSAGE_LIST_SAVING_FINISHED';

export const MESSAGE_LIST_UPDATE = 'MESSAGE_LIST_UPDATE';
export const MESSAGE_LIST_UPDATE_STARTED = 'MESSAGE_LIST_UPDATE_STARTED';
export const MESSAGE_LIST_UPDATE_FINISHED = 'MESSAGE_LIST_UPDATE_FINISHED';

export const CHANNEL_LIST_ITEM_CREATE = 'CHANNEL_LIST_ITEM_CREATE';
export const CHANNEL_LIST_ITEM_UPDATE = 'CHANNEL_LIST_ITEM_UPDATE';
export const CHANNEL_LIST_ITEM_DELETE = 'CHANNEL_LIST_ITEM_DELETE';
export const CHANNEL_LIST_ITEM_SELECT = 'CHANNEL_LIST_ITEM_SELECT';
export const CHANNEL_LIST_ITEM_MOVE = 'CHANNEL_LIST_ITEM_MOVE';
export const CHANNEL_LIST_ITEM_START_EDITING = 'CHANNEL_LIST_ITEM_START_EDITING';
export const CHANNEL_LIST_ITEM_CANCEL_EDITING = 'CHANNEL_LIST_ITEM_CANCEL_EDITING';
export const CHANNEL_LIST_OPEN_CREATE_NEW_FORM = 'CHANNEL_LIST_OPEN_CREATE_NEW_FORM';
export const CHANNEL_LIST_CLOSE_CREATE_NEW_FORM = 'CHANNEL_LIST_CLOSE_CREATE_NEW_FORM';
export const CHANNEL_LIST_ITEM_START_DRAGGING = 'CHANNEL_LIST_ITEM_START_DRAGGING';
export const CHANNEL_LIST_ITEM_STOP_DRAGGING = 'CHANNEL_LIST_ITEM_STOP_DRAGGING';
export const CHANNEL_LIST_SAVING_STARTED = 'CHANNEL_LIST_SAVING_STARTED';
export const CHANNEL_LIST_SAVING_FINISHED = 'CHANNEL_LIST_SAVING_FINISHED';
export const CHANNEL_LIST_ITEM_INVITE_USER = 'CHANNEL_LIST_ITEM_INVITE_USER';

export const CHANNEL_LIST_UPDATE = 'CHANNEL_LIST_UPDATE';
export const CHANNEL_LIST_UPDATE_STARTED = 'CHANNEL_LIST_UPDATE_STARTED';
export const CHANNEL_LIST_UPDATE_FINISHED = 'CHANNEL_LIST_UPDATE_FINISHED';

export const PROFILE_UPDATE_DETAILS = 'PROFILE_UPDATE_DETAILS';
export const PROFILE_UPDATE_AVATAR = 'PROFILE_UPDATE_AVATAR';
export const PROFILE_FETCHING_STARTED = 'PROFILE_FETCHING_STARTED';
export const PROFILE_FETCHING_FAILED = 'PROFILE_FETCHING_FAILED';
export const PROFILE_UPLOADING_FAILED = 'PROFILE_UPLOADING_FAILED';
export const PROFILE_AVATAR_UPLOADING_STARTED = 'PROFILE_AVATAR_UPLOADING_STARTED';
export const PROFILE_AVATAR_UPLOADING_FAILED = 'PROFILE_AVATAR_UPLOADING_FAILED';
export const PROFILE_AVATAR_FETCHING_STARTED = 'PROFILE_AVATAR_FETCHING_STARTED';
export const PROFILE_AVATAR_FETCHING_FAILED = 'PROFILE_AVATAR_FETCHING_FAILED';

export const SHARED_RECEIVE_TOKEN = 'SHARED_RECEIVE_TOKEN';
export const SHARED_INVALIDATE_TOKEN = 'SHARED_INVALIDATE_TOKEN';
export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_AUTHENTICATION_FAILED = 'SHARED_AUTHENTICATION_FAILED';
export const SHARED_DISMISS_ERROR = 'SHARED_DISMISS_ERROR';

export const USERS_LIST_UPDATE = 'USERS_LIST_UPDATE';
